openapi: "3.0.0"
info:
  version: "1.0"
  title: Easy Server Warehouse
  description: Сервер склада
servers:
  - url: http://localhost:8080/v1
tags:
  - name: products
paths:
  /api/products:
    get:
      summary: Возвращает список товаров склада
      operationId: listProducts
      tags:
        - products
      parameters:
        - name: limit
          in: query
          description: Лимит возвращаемых товаров
          required: false
          schema:
            type: integer
            format: int32
        - name: page
          in: query
          description: Номер страницы
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

components:
  schemas:
    Weight:
      properties:
        amount:
          description: Количество
          type: number
          format: double
          example: 1.4
        unit:
          description: Единица измерения
          type: string
          example: кг
    Product:
      properties:
        id:
          description: Идентификатор товара
          type: integer
          format: int64
          example: 1
        name:
          description: Наименование товара
          type: string
          example: Хлеб



